logging:
  level:
    root: INFO
spring:
  thymeleaf:
    cache: false
server:
  port: 8888

---
spring:
    profiles:
      #active: test
logging:
    level: DEBUG
---
spring:
  profiles:
    active: product

logging:
  path: /tmp/
  file: BookWorm.log
  level:
    root: WRAN